apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["start-dev", "--import-realm"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-import
              mountPath: /opt/keycloak/data/import
          env:
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.adminUser | quote }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: {{ .Values.adminPassword | quote }}
            - name: KC_HOSTNAME
              value: {{ .Values.hostname | quote }}
            - name: KC_HOSTNAME_STRICT
              value: {{ .Values.hostnameStrict | quote }}
            - name: KC_PROXY_HEADERS
              value: {{ .Values.proxyHeaders | quote }}
            - name: KC_HTTP_ENABLED
              value: {{ .Values.httpEnabled | quote }}
            - name: JAVA_OPTS
              value: {{ .Values.javaOpts | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
      volumes:
        - name: realm-import
          configMap:
            name: {{ include "keycloak.fullname" . }}-realm
