apiVersion: v1
kind: Secret
metadata:
  name: infra-secrets
  namespace: infra
type: Opaque
stringData:
  POSTGRES_USER: "${PG_SUPERUSER:-postgres}"
  POSTGRES_PASSWORD: "${PG_SUPERUSER_PASSWORD:-postgres_super_secret_2026}"
  POSTGRES_DB: "${PG_DATABASE:-postgres}"
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-root_secret_2026}"
  MYSQL_DATABASE: "${MYSQL_DATABASE:-appdb}"
  MYSQL_USER: "${MYSQL_USER:-appuser}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD:-appuser_secret_2026}"
  GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER:-admin}"
  GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD:-admin_secret_2026}"
  GF_INSTALL_PLUGINS: "${GRAFANA_PLUGINS:-}"
