apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver-pvc
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoserver
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  template:
    metadata:
      labels:
        app: geoserver
    spec:
      containers:
        - name: geoserver
          image: docker.osgeo.org/geoserver:2.25.2
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms128m -Xmx512m"
            - name: INSTALL_EXTENSIONS
              value: "true"
          volumeMounts:
            - name: geoserver-data
              mountPath: /opt/geoserver/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "768Mi"
              cpu: "500m"
      volumes:
        - name: geoserver-data
          persistentVolumeClaim:
            claimName: geoserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: geoserver
  namespace: infra
spec:
  selector:
    app: geoserver
  ports:
    - port: 8080
      targetPort: 8080
