apiVersion: v1
kind: Secret
metadata:
  name: geostack-secrets
  namespace: infra
type: Opaque
stringData:
  POSTGRES_PASSWORD: "geostack_dev"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
  JWT_SECRET: "change-me-in-production"
