# Inventory — isi IP VPS target
# Variables dari root DEVOPS/.env
all:
  children:
    k3s_server:
      hosts:
        # vps1:
        #   ansible_host: 192.168.1.10
        #   ansible_user: ubuntu
      vars:
        tailscale_args: "{{ lookup('env', 'TAILSCALE_ARGS') }}"
        letsencrypt_email: "{{ lookup('env', 'LETSENCRYPT_EMAIL') }}"

    k3s_agent:
      hosts:
        # agent1:
        #   ansible_host: 192.168.1.11
        #   ansible_user: ubuntu
      vars:
        tailscale_args: "{{ lookup('env', 'TAILSCALE_ARGS') }}"
