#!/bin/bash
# Create app database + user — from container env vars
set -e

APP_USER="${APP_USER:-appuser}"
APP_PASSWORD="${APP_PASSWORD:-appuser_secret_2026}"
APP_DB="${APP_DB:-appdb}"

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<SQL
CREATE DATABASE ${APP_DB}
    WITH OWNER = ${POSTGRES_USER}
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    TEMPLATE = template0
    CONNECTION LIMIT = -1;

\c ${APP_DB}

CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
GRANT CONNECT ON DATABASE ${APP_DB} TO ${APP_USER};
GRANT ALL ON SCHEMA public TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${APP_USER};

CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS logs;
CREATE SCHEMA IF NOT EXISTS vectors;
CREATE SCHEMA IF NOT EXISTS geo;

GRANT ALL ON SCHEMA analytics, logs, vectors, geo TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics, logs, vectors, geo GRANT ALL ON TABLES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics, logs, vectors, geo GRANT ALL ON SEQUENCES TO ${APP_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics, logs, vectors, geo GRANT ALL ON FUNCTIONS TO ${APP_USER};
SQL

echo "✓ App DB '${APP_DB}' + user '${APP_USER}' created"
