apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  chart: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: ${INGRESS_NGINX_VERSION}
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      hostPort:
        enabled: true
      service:
        type: ClusterIP
