apiVersion: v1
kind: Secret
metadata:
  name: infra-secrets
  namespace: infra
type: Opaque
stringData:
  POSTGRES_USER: "${PG_SUPERUSER}"
  POSTGRES_PASSWORD: "${PG_SUPERUSER_PASSWORD}"
  POSTGRES_DB: "${PG_DATABASE}"
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_DATABASE: "${MYSQL_DATABASE}"
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER}"
  GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD}"
  GF_INSTALL_PLUGINS: "${GRAFANA_PLUGINS}"
  EMQX_DASHBOARD_PASSWORD: "${EMQX_DASHBOARD_PASSWORD}"
