apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: ewallet
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "25"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: wasteco
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "25"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: resolva
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "25"

