output "instance_id" {
  description = "Vultr Instance ID"
  value       = vultr_instance.this.id
}

output "public_ip" {
  description = "Public IPv4 address of the instance"
  value       = vultr_instance.this.main_ip
}

output "internal_ip" {
  description = "Internal/Private IP address"
  value       = vultr_instance.this.internal_ip
}

output "default_password" {
  description = "Default root password generated by Vultr (if no SSH key supplied)"
  value       = vultr_instance.this.default_password
  sensitive   = true
}
