apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: infra
  annotations:
    tailscale.com/hostname: mysql-faisalaffan
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: infra
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:${MYSQL_VERSION}
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: infra-secrets
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            requests:
              memory: "${K8S_REQUESTS_MEMORY}"
              cpu: "${K8S_REQUESTS_CPU}"
            limits:
              memory: "${MYSQL_MEMORY_LIMIT}"
              cpu: "${K8S_LIMITS_CPU}"
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: ${MYSQL_DATA_SIZE}
