# ============================================================
# Global vars — semua node
# ============================================================

ansible_python_interpreter: /usr/bin/python3

# Tailscale (authkey di vault.yml)
tailscale_version: stable
tailscale_args: "--accept-routes"

# Repo infra
infra_repo: git@github.com:faisalaffan/infra-light.git
infra_dir: /opt/infra-light
infra_branch: dev
